version: '3.7'
services:
  mongo_db:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongo_db
    volumes:
      - mongo_db_data_container:/data/db
    networks:
      - shared-net

  auth_service:
    build: ./auth-service
    ports:
      - "5001:5000"
    depends_on:
      - mongo_db
    container_name: auth_service
    environment:
      - MONGO_URI='mongodb://mongo_db:27017/products_db'
      - JWT_SECRET='secret'
    networks:
      - shared-net
  
  frontend:
    build: ./frontend/
    ports:
      - "82:80"
    depends_on:
      - auth_service
      - product_service
    container_name: frontend
    networks:
      - shared-net

  product_service:
    build:
      context: ./products-service/
    ports:
      - 8080:8080
    container_name: product_service
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=products_db
    depends_on:
      - mongo_db
    networks:
      - shared-net

volumes:
  mongo_db_data_container:

networks:
  shared-net:
    driver: bridge
